# Generated by Django 2.2.4 on 2020-11-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(default=("2016-7-16")),
            preserve_default=False,
        ),
    ]
