# Generated by Django 2.2.4 on 2020-11-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0002_show_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
